name: Application testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build and test affected apps
        run: |
          npx nx format:check
          npx nx affected --target=lint --all --parallel --max-parallel=3
          npx nx affected --target=test --all --parallel --max-parallel=3 --ci --code-coverage
